name: autharization_hanna
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2
  gap: ^3.0.1
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  infinite_scroll_pagination: ^4.0.0
  percent_indicator: ^4.2.3
  share_plus: ^4.0.10
  just_audio: ^0.9.36


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSansMobile_Medium.ttf
          weight: 400