name: hafez
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+2
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2
  gap: ^3.0.1
  pinput: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  percent_indicator: ^4.2.3
  share_plus: ^4.0.10
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  device_preview: ^1.1.0
  url_launcher: ^6.2.3
  flutter_launcher_icons: ^0.13.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  # hive_generator: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSansMobile_Medium.ttf
          weight: 100
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher.png"

