// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXuUa2hIyEjH3S8X92oMML2wz-yXbVoY',
    appId: '1:82379110110:web:995dda18e0fc976bc1b44f',
    messagingSenderId: '82379110110',
    projectId: 'hafeznameh-new',
    authDomain: 'hafeznameh-new.firebaseapp.com',
    storageBucket: 'hafeznameh-new.appspot.com',
    measurementId: 'G-FZMWT17T92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3XMtn2WPQf-T70ilWU716ybbWxY7kWk',
    appId: '1:82379110110:android:43d379967b67320dc1b44f',
    messagingSenderId: '82379110110',
    projectId: 'hafeznameh-new',
    storageBucket: 'hafeznameh-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwUtKe7UkrItH4BNAjr186UAR_Dk-IHI',
    appId: '1:82379110110:ios:787952fb8c2ba722c1b44f',
    messagingSenderId: '82379110110',
    projectId: 'hafeznameh-new',
    storageBucket: 'hafeznameh-new.appspot.com',
    iosBundleId: 'com.example.autharizationHanna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwUtKe7UkrItH4BNAjr186UAR_Dk-IHI',
    appId: '1:82379110110:ios:8063ca54d110309dc1b44f',
    messagingSenderId: '82379110110',
    projectId: 'hafeznameh-new',
    storageBucket: 'hafeznameh-new.appspot.com',
    iosBundleId: 'com.example.autharizationHanna.RunnerTests',
  );
}
